### ISSUE TITLE
incorrect number formatting used on transactions

### ISSUE THREAD

**Issue by nc-2k** [twali-xyz/drippi#64]
seems to be using accounting format $(xx,xxx.xx). 

it should be -$00,000.00

<img width="213" alt="image" src="https://user-images.githubusercontent.com/108298225/229243742-a774212b-f42b-4961-b18b-c8a0afe3e6f3.png">

**Comment by hone1er** [comment]
Ah man I had it like that but changed to what I guess was an old design lol. Will fix

**Comment by hone1er** [comment]
Done
