### ISSUE TITLE
plaid cannot connect to Chase due to me having no liabilities account

### ISSUE THREAD

**Issue by nc-2k** [twali-xyz/drippi#78]
when choosing chase (and amex, but chase is more improtant) as a bank, it connects with chase, fires the chase oauth sequence and connects, but then at the point where Plaid shows the accouint connect it fails as I have no liabilities accounts at Chase

video attached for flow

assuming we dont want to be connecting to banks, looking for liabilities accounts

https://user-images.githubusercontent.com/108298225/230210239-02a0ff74-6f12-458b-b169-33aca9e0488f.mov

**Comment by ivyastrix** [comment]
wontfix since we don't use liabilities anymore!
